# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_exam_app', '0002_auto_20171117_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='placeholder username', max_length=255),
            preserve_default=False,
        ),
    ]
